services:
  api:
    build: .
    container_name: indexador-api
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 9100
    ports:
      - "9102:9100"
    env_file:
      - .env
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./data:/app/data
      - /home/janailsonf-a/teste_10m:/data/indexados
    restart: unless-stopped

  indexer:
    build: .
    container_name: indexador-worker
    command: /app/scripts/run_indexer.sh
    env_file:
      - .env
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./data:/app/data
      - /home/janailsonf-a/teste_10m:/data/indexados
    restart: unless-stopped